import type { Locale } from "@cloudbridge/contracts";

export const isLocale = (value: string): value is Locale => value === "zh" || value === "en";

export const copy = {
  zh: {
    brandPrimary: "云桥",
    brandSecondary: "CloudBridge",
    navServices: "服务",
    navSupport: "联系支持",
    customerSupport: "客户服务",
    languageLabel: "语言切换",
    languageZh: "中文",
    languageEn: "英文",
    capabilityGlobal: "全球币种",
    capabilityPricing: "双价格桥接",
    capabilityContact: "单一联系方式下单",
    capabilitySupport: "人工服务接力",
    catalogTitle: "AI 服务阵列",
    catalogSubtitle: "精选主流 AI 工具，以清楚的价格与库存信息呈现。",
    searchPlaceholder: "输入商品名称开始搜索",
    searchLabel: "搜索商品",
    categoryLabel: "商品分类",
    currencyLabel: "选择币种",
    categoryAll: "全部服务",
    loading: "正在连接服务目录",
    loadError: "服务目录暂时无法连接",
    refreshFailed: "刷新未完成，当前仍显示上一次的数据。",
    offline: "网络连接已断开，请恢复网络后重试。",
    slowNetwork: "网络响应较慢，我们仍在等待服务器返回。",
    retry: "重新连接",
    emptyTitle: "没有找到匹配的服务",
    emptyBody: "请尝试更短的关键词，或切换到其他分类。",
    soldOut: "暂时售罄",
    lowStock: (count: number) => `仅余 ${count} 份`,
    available: "可下单",
    viewProduct: "查看服务",
    from: "当前价格",
    dualPrice: "参考价格",
    backHome: "返回首页",
    serviceLabel: "服务",
    detailTitle: "服务说明",
    policyLabel: "云桥 / 政策",
    orderTitle: "提交人工确认订单",
    orderBody: "选择一个联系方式。客服将通过该渠道确认服务与付款信息。",
    contactChannel: "联系方式",
    contactValue: "联系账号",
    contactPlaceholder: "填写对应账号、号码或邮箱",
    contactError: "请填写至少 4 个字符的有效联系账号。",
    policyAccept: "我已阅读并接受服务条款与隐私说明",
    policyError: "提交前需要接受服务条款与隐私说明。",
    submitOrder: "提交订单",
    retryOrder: "重新提交订单",
    ordersPaused: "暂停接单",
    ordersPausedBody: "当前暂停接受新订单，商品信息仍可正常浏览。",
    contactChannelsUnavailable: "暂无联系方式",
    contactChannelsUnavailableBody: "当前没有可用的联系渠道，请稍后再试。",
    supportUnavailableTitle: "客服暂未开放",
    supportUnavailableBody: "当前没有已启用的客服渠道，请稍后再试。",
    orderConfigurationUpdated: "商品价格、政策或联系渠道已更新，请确认最新信息后重新提交。",
    submitting: "正在安全提交",
    orderSuccess: "连接已建立",
    orderSuccessBody: "订单已进入人工确认流程，请留意你选择的联系方式。",
    orderNumber: "订单号",
    orderFailed: "订单暂时无法提交，请检查信息后重试。",
    imageUnavailable: "图片暂时无法显示",
    terms: "服务条款",
    privacy: "隐私说明",
    footerCatalog: "服务目录",
    footerSupport: "人工服务",
    footerSupportBody: "提交订单后，通过所选联系方式继续确认。",
    footerPolicies: "政策与保障",
    footerNote: "人工确认订单 · 不提供公开订单查询",
    transitService: "中转站服务",
    transitUnavailable: "中转站地址尚未配置，请稍后再试。",
  },
  en: {
    brandPrimary: "CloudBridge",
    brandSecondary: "",
    navServices: "Services",
    navSupport: "Support",
    customerSupport: "Customer Support",
    languageLabel: "Language switch",
    languageZh: "Chinese",
    languageEn: "English",
    capabilityGlobal: "Global currencies",
    capabilityPricing: "Dual-price bridge",
    capabilityContact: "One-contact ordering",
    capabilitySupport: "Human support handoff",
    catalogTitle: "AI service collection",
    catalogSubtitle: "Mainstream AI tools presented with clear pricing and availability.",
    searchPlaceholder: "Search by product name",
    searchLabel: "Search products",
    categoryLabel: "Product categories",
    currencyLabel: "Select currency",
    categoryAll: "All services",
    loading: "Connecting to the service catalog",
    loadError: "The service catalog is temporarily unavailable",
    refreshFailed: "Refresh did not complete. The previous data remains visible.",
    offline: "You are offline. Reconnect and try again.",
    slowNetwork: "The network is taking longer than usual. We are still waiting for the server.",
    retry: "Reconnect",
    emptyTitle: "No matching services",
    emptyBody: "Try a shorter keyword or choose another category.",
    soldOut: "Sold out",
    lowStock: (count: number) => `Only ${count} left`,
    available: "Available",
    viewProduct: "View service",
    from: "Current price",
    dualPrice: "Reference",
    backHome: "Back home",
    serviceLabel: "Service",
    detailTitle: "Service notes",
    policyLabel: "CloudBridge / Policy",
    orderTitle: "Submit a manual-confirmation order",
    orderBody: "Choose one contact channel. Support will confirm service and payment details there.",
    contactChannel: "Contact channel",
    contactValue: "Contact account",
    contactPlaceholder: "Enter the relevant account, number or email",
    contactError: "Enter a valid contact account with at least 4 characters.",
    policyAccept: "I have read and accept the terms and privacy notice",
    policyError: "Accept the terms and privacy notice before submitting.",
    submitOrder: "Submit order",
    retryOrder: "Retry order",
    ordersPaused: "Orders paused",
    ordersPausedBody: "New orders are paused. Product information remains available.",
    contactChannelsUnavailable: "Contact unavailable",
    contactChannelsUnavailableBody: "No contact channel is currently available. Please try again later.",
    supportUnavailableTitle: "Customer support is not available yet",
    supportUnavailableBody: "There are no enabled support channels right now. Please try again later.",
    orderConfigurationUpdated: "The product price, policy, or contact channels changed. Review the latest details and submit again.",
    submitting: "Submitting securely",
    orderSuccess: "Connection established",
    orderSuccessBody: "Your order is awaiting manual confirmation. Watch your selected contact channel.",
    orderNumber: "Order number",
    orderFailed: "The order could not be submitted. Check the details and try again.",
    imageUnavailable: "Image unavailable",
    terms: "Terms",
    privacy: "Privacy",
    footerCatalog: "Catalog",
    footerSupport: "Human support",
    footerSupportBody: "Continue through your selected contact channel after ordering.",
    footerPolicies: "Policies & assurance",
    footerNote: "Manual confirmation · No public order lookup",
    transitService: "Transit Service",
    transitUnavailable: "The transit service URL is not configured yet.",
  },
} as const;
