export const currencies = [
  { code: "MYR", token: "RM", name: { zh: "马来西亚林吉特", en: "Malaysian Ringgit" }, rate: 1, digits: 2 },
  { code: "CNY", token: "CN¥", name: { zh: "人民币", en: "Chinese Yuan" }, rate: 1.62, digits: 2 },
  { code: "USD", token: "$", name: { zh: "美元", en: "US Dollar" }, rate: 0.235, digits: 2 },
  { code: "SGD", token: "S$", name: { zh: "新加坡元", en: "Singapore Dollar" }, rate: 0.316, digits: 2 },
  { code: "EUR", token: "€", name: { zh: "欧元", en: "Euro" }, rate: 0.216, digits: 2 },
  { code: "GBP", token: "£", name: { zh: "英镑", en: "British Pound" }, rate: 0.184, digits: 2 },
  { code: "JPY", token: "JP¥", name: { zh: "日元", en: "Japanese Yen" }, rate: 35.4, digits: 0 },
  { code: "IDR", token: "Rp", name: { zh: "印度尼西亚盾", en: "Indonesian Rupiah" }, rate: 3820, digits: 0 },
  { code: "USDT", token: "₮", name: { zh: "泰达币", en: "Tether" }, rate: 0.236, digits: 2 },
];

export const heroes = [
  {
    image: "/assets/hero-main.webp",
    eyebrow: { zh: "云桥 / 01", en: "CLOUDBRIDGE / 01" },
    title: { zh: "全球 AI 工具，\n在一座桥上相遇", en: "Global AI tools,\nconnected by one bridge" },
    copy: {
      zh: "从 Codex 到 Gemini，让工具、价格与人工服务在一个入口汇合。",
      en: "From Codex to Gemini, tools, pricing and human support meet in one considered place.",
    },
    cta: { zh: "探索全部服务", en: "Explore services" },
    target: "products",
    tone: "cyan",
  },
  {
    image: "/assets/hero-codex.webp",
    eyebrow: { zh: "开发工作流 / 02", en: "DEVELOPMENT / 02" },
    title: { zh: "让 Codex 进入\n真实开发工作流", en: "Bring Codex into\nyour real workflow" },
    copy: {
      zh: "从需求理解、代码修改到执行验证，让开发过程保持连贯。",
      en: "Move from requirements and code changes to execution and verification without breaking flow.",
    },
    cta: { zh: "查看 Codex", en: "View Codex" },
    target: "codex",
    tone: "blue",
  },
  {
    image: "/assets/hero-gemini.webp",
    eyebrow: { zh: "多模态协作 / 03", en: "MULTIMODAL / 03" },
    title: { zh: "文字、图像与思考，\n汇入多模态空间", en: "Text, image and thought,\nin one multimodal space" },
    copy: {
      zh: "通过 Gemini 连接文档、视觉与复杂问题，让信息不再割裂。",
      en: "Connect documents, visuals and complex questions with Gemini in a unified flow.",
    },
    cta: { zh: "查看 Gemini", en: "View Gemini" },
    target: "gemini",
    tone: "violet",
  },
  {
    image: "/assets/hero-currency.webp",
    eyebrow: { zh: "全球定价 / 04", en: "GLOBAL PRICING / 04" },
    title: { zh: "当地货币与 USDT，\n双价格清楚呈现", en: "Local currency and USDT,\npresented with clarity" },
    copy: {
      zh: "根据所在国家显示建议币种，也可以随时手动切换。",
      en: "See a suggested local currency for your region, or switch manually at any time.",
    },
    cta: { zh: "查看价格", en: "View pricing" },
    target: "products",
    tone: "green",
  },
];

export const productCategories = [
  {
    id: "development",
    name: { zh: "编码开发", en: "Coding & development" },
    active: true,
    order: 1,
  },
  {
    id: "assistant",
    name: { zh: "通用助手", en: "General assistants" },
    active: true,
    order: 2,
  },
  {
    id: "research",
    name: { zh: "研究效率", en: "Research & productivity" },
    active: true,
    order: 3,
  },
  {
    id: "creative",
    name: { zh: "图像创作", en: "Image creation" },
    active: true,
    order: 4,
  },
];

export const products = [
  {
    id: "codex",
    categoryId: "development",
    image: "/assets/product-codex.webp",
    name: { zh: "OpenAI Codex 专业版", en: "OpenAI Codex Professional" },
    kicker: { zh: "开发工作流", en: "Developer workflow" },
    price: 89,
    compare: 109,
    usdt: 21.04,
    stock: 12,
    description: {
      zh: "适合希望把需求理解、代码修改、执行与验证串联起来的开发者。提交订单后，客服会根据你填写的联系方式确认服务方式与交付信息。",
      en: "For developers who want requirements, code changes, execution and verification in one connected workflow. Support will confirm delivery through your chosen contact channel.",
    },
  },
  {
    id: "gemini",
    categoryId: "assistant",
    image: "/assets/product-gemini.webp",
    name: { zh: "Gemini Advanced", en: "Gemini Advanced" },
    kicker: { zh: "多模态协作", en: "Multimodal work" },
    price: 79,
    compare: 99,
    usdt: 18.68,
    stock: 8,
    description: {
      zh: "面向文字、图片、文档与复杂任务的多模态 AI 服务。页面展示价格为当前预览币种的设计效果。",
      en: "A multimodal AI service for text, image, documents and complex tasks. Displayed pricing demonstrates the selected preview currency.",
    },
  },
  {
    id: "chatgpt",
    categoryId: "assistant",
    image: "/assets/product-chatgpt.webp",
    name: { zh: "ChatGPT Plus", en: "ChatGPT Plus" },
    kicker: { zh: "通用智能助手", en: "General AI assistant" },
    price: 92,
    compare: 119,
    usdt: 21.75,
    stock: Infinity,
    description: {
      zh: "适用于写作、分析、学习与日常知识工作的通用 AI 服务。无需注册商城账号即可提交订单。",
      en: "A general AI service for writing, analysis, learning and everyday knowledge work. No store account is required to submit an order.",
    },
  },
  {
    id: "claude",
    categoryId: "assistant",
    image: "/assets/product-claude.webp",
    name: { zh: "Claude Pro", en: "Claude Pro" },
    kicker: { zh: "长文与推理", en: "Long-form reasoning" },
    price: 85,
    compare: 108,
    usdt: 20.09,
    stock: 3,
    description: {
      zh: "适合长文阅读、结构化写作与复杂问题分析。低库存状态会以克制的琥珀节点提示。",
      en: "Built for long-form reading, structured writing and complex analysis. Low inventory is signalled with a restrained amber node.",
    },
  },
  {
    id: "cursor",
    categoryId: "development",
    image: "/assets/product-cursor.webp",
    name: { zh: "Cursor Pro", en: "Cursor Pro" },
    kicker: { zh: "AI 代码编辑器", en: "AI code editor" },
    price: 76,
    compare: 96,
    usdt: 17.97,
    stock: 15,
    description: {
      zh: "面向实际代码库工作的 AI 编辑体验，适合高频编程和项目维护。",
      en: "An AI editor experience made for real codebases, frequent coding and project maintenance.",
    },
  },
  {
    id: "perplexity",
    categoryId: "research",
    image: "/assets/product-perplexity.webp",
    name: { zh: "Perplexity Pro", en: "Perplexity Pro" },
    kicker: { zh: "研究与检索", en: "Research and search" },
    price: 72,
    compare: 90,
    usdt: 17.02,
    stock: 9,
    description: {
      zh: "为资料检索、来源整理与快速研究打造的 AI 服务。",
      en: "An AI service designed for research, source discovery and rapid synthesis.",
    },
  },
  {
    id: "copilot",
    categoryId: "development",
    image: "/assets/product-copilot.webp",
    name: { zh: "GitHub Copilot", en: "GitHub Copilot" },
    kicker: { zh: "编码辅助", en: "Coding assistant" },
    price: 68,
    compare: 86,
    usdt: 16.07,
    stock: Infinity,
    description: {
      zh: "适合在编辑器与代码托管工作流中使用的智能编码辅助服务。",
      en: "An intelligent coding assistant for editor and repository workflows.",
    },
  },
  {
    id: "midjourney",
    categoryId: "creative",
    image: "/assets/product-midjourney.webp",
    name: { zh: "Midjourney Standard", en: "Midjourney Standard" },
    kicker: { zh: "视觉生成", en: "Visual generation" },
    price: 118,
    compare: 148,
    usdt: 27.89,
    stock: 0,
    description: {
      zh: "面向视觉创意与图像生成的服务。当前演示为售罄状态，用于检查完整界面反馈。",
      en: "A service for visual ideation and image generation. This preview intentionally shows the sold-out state.",
    },
  },
];

export const merchantChannels = [
  { type: "whatsapp", mode: "direct-link", label: { zh: "WhatsApp", en: "WhatsApp" }, account: "+60 12 888 6618", rawAccount: "60128886618", hours: "10:00–22:00", direct: true },
  { type: "email", mode: "direct-link", label: { zh: "电子邮件", en: "Email" }, account: "support@cloudbridge.test", rawAccount: "support@cloudbridge.test", hours: "24 小时内回复", direct: true },
  { type: "telegram", mode: "direct-link", label: { zh: "Telegram", en: "Telegram" }, account: "@CloudBridgeSupport", rawAccount: "CloudBridgeSupport", hours: "10:00–22:00", direct: true },
  { type: "wechat", mode: "qr-copy", label: { zh: "微信", en: "WeChat" }, account: "CloudBridge_AI", hours: "10:00–22:00", direct: false },
  { type: "qq", mode: "direct-with-fallback", label: { zh: "QQ", en: "QQ" }, account: "288661812", rawAccount: "288661812", hours: "10:00–22:00", direct: true },
];

export const mockOrders = [
  { id: "CB-260727-8K3P9M", product: "OpenAI Codex", amount: "RM 89.00", usdt: "21.04 USDT", contact: "+60 12****6789", fullContact: "+60 12 3456 6789", channel: "WhatsApp", status: "new", payment: "unpaid", assignee: { zh: "未分配", en: "Unassigned" }, createdAt: "2026-07-27T14:32:00-07:00" },
  { id: "CB-260727-H2Q8LX", product: "Gemini Advanced", amount: "USD 18.57", usdt: "18.68 USDT", contact: "gem****88", fullContact: "gemini_user88", channel: "WeChat", status: "contacted", payment: "pending", assignee: { zh: "林澄", en: "Lin Cheng" }, createdAt: "2026-07-27T13:18:00-07:00" },
  { id: "CB-260727-P7M4CW", product: "Claude Pro", amount: "SGD 26.86", usdt: "20.09 USDT", contact: "28****812", fullContact: "288661812", channel: "QQ", status: "processing", payment: "paid", assignee: { zh: "陈予", en: "Chen Yu" }, createdAt: "2026-07-27T11:46:00-07:00" },
  { id: "CB-260726-N9D6KA", product: "ChatGPT Plus", amount: "MYR 92.00", usdt: "21.75 USDT", contact: "+60 16****2011", fullContact: "+60 16 9820 2011", channel: "WhatsApp", status: "completed", payment: "paid", assignee: { zh: "林澄", en: "Lin Cheng" }, createdAt: "2026-07-26T18:20:00-07:00" },
];

export const teamMembers = [
  { name: { zh: "王朝", en: "Wang Chao" }, email: "wang@cloudbridge.test", role: { zh: "超级管理员", en: "Super admin" }, group: { zh: "管理层", en: "Management" }, status: "online", lastActiveAt: "2026-07-27T14:40:00-07:00", avatar: "王", twoFactor: true, sessions: 2 },
  { name: { zh: "林澄", en: "Lin Cheng" }, email: "lin@cloudbridge.test", role: { zh: "订单客服", en: "Order support" }, group: { zh: "客户服务", en: "Customer service" }, status: "online", lastActiveAt: "2026-07-27T14:36:00-07:00", avatar: "林", twoFactor: true, sessions: 1 },
  { name: { zh: "陈予", en: "Chen Yu" }, email: "chen@cloudbridge.test", role: { zh: "财务审核", en: "Finance reviewer" }, group: { zh: "财务", en: "Finance" }, status: "offline", lastActiveAt: "2026-07-27T12:18:00-07:00", avatar: "陈", twoFactor: false, sessions: 0 },
  { name: { zh: "Mia Tan", en: "Mia Tan" }, email: "mia@cloudbridge.test", role: { zh: "内容编辑", en: "Content editor" }, group: { zh: "内容运营", en: "Content operations" }, status: "online", lastActiveAt: "2026-07-27T14:24:00-07:00", avatar: "M", twoFactor: false, sessions: 1 },
];

export const auditEvents = [
  { type: "CONTACT_REVEALED", actor: { zh: "林澄", en: "Lin Cheng" }, target: "CB-260727-8K3P9M", createdAt: "2026-07-27T14:36:00-07:00", tone: "warning" },
  { type: "TRANSLATION_UPDATED", actor: { zh: "Mia Tan", en: "Mia Tan" }, target: "Gemini Advanced", createdAt: "2026-07-27T14:08:00-07:00", tone: "normal" },
  { type: "PAYMENT_CONFIRMED", actor: { zh: "陈予", en: "Chen Yu" }, target: "CB-260727-P7M4CW", createdAt: "2026-07-27T12:03:00-07:00", tone: "success" },
  { type: "RATES_REFRESHED", actor: { zh: "系统任务", en: "System job" }, target: "23", createdAt: "2026-07-27T11:30:00-07:00", tone: "normal" },
];

export const statusText = {
  new: { zh: "新订单", en: "New" },
  manualPending: { zh: "待人工处理", en: "Manual review" },
  contacted: { zh: "已联系", en: "Contacted" },
  awaitingPayment: { zh: "待付款", en: "Awaiting payment" },
  paymentProcessing: { zh: "支付处理中", en: "Payment processing" },
  processing: { zh: "处理中", en: "Processing" },
  fulfilling: { zh: "交付中", en: "Fulfilling" },
  completed: { zh: "已完成", en: "Completed" },
  cancelled: { zh: "已取消", en: "Cancelled" },
  refundPending: { zh: "退款中", en: "Refund pending" },
  refunded: { zh: "已退款", en: "Refunded" },
  disputed: { zh: "争议中", en: "Disputed" },
  unpaid: { zh: "未付款", en: "Unpaid" },
  pending: { zh: "待确认", en: "Pending" },
  paid: { zh: "已付款", en: "Paid" },
  failed: { zh: "失败", en: "Failed" },
  disabled: { zh: "未启用", en: "Disabled" },
};

export const copy = {
  zh: {
    brandName: "云桥 CloudBridge",
    homeLabel: "CloudBridge 首页",
    previousStory: "上一张",
    nextStory: "下一张",
    capabilitiesLabel: "CloudBridge 服务能力",
    languageChinese: "中文",
    languageEnglish: "英文",
    brandLine: "连接全球 AI 服务",
    orderLookup: "订单查询",
    contactSupport: "联系客服",
    productsTitle: "AI 服务陈列",
    productsCopy: "精选主流 AI 工具，以清楚的价格与库存信息呈现。",
    discoverTitle: "今天想连接什么 AI 服务？",
    searchProducts: "输入商品名称开始搜索",
    categoryAll: "全部",
    noResultsTitle: "没有找到匹配的服务",
    noResultsCopy: "尝试缩短关键词，或切换到其他分类。",
    clearSearch: "清空搜索",
    serviceCapabilities: "服务能力",
    currentCurrency: "当前币种",
    allServices: "全部服务",
    localPrice: "当地货币",
    usdtReference: "USDT 参考",
    stock: "库存",
    inStock: "现货",
    lowStock: "仅剩 {count}",
    soldOut: "暂时售罄",
    buyNow: "立即下单",
    viewDetail: "查看详情",
    contactTitle: "需要先确认？让客服接上这座桥",
    contactCopy: "选择你习惯的渠道，咨询商品、付款与交付方式。",
    footerLine: "连接工具、价格与可信服务。",
    privacy: "隐私政策",
    terms: "服务条款",
    refund: "售后退款",
    delivery: "数字服务交付",
    cookies: "Cookie 与追踪",
    language: "语言",
    currency: "币种",
    autoRecommend: "根据所在地区建议",
    buyTitle: "提交订单",
    contactType: "联系方式类型",
    contactValue: "联系方式",
    submitOrder: "确认提交",
    submitting: "正在连接订单",
    consent: "提交即表示同意商家使用该联系方式处理本次订单。",
    requiredError: "请输入联系方式",
    formatError: "联系方式格式不正确，请检查后重试",
    successTitle: "订单待人工处理",
    successCopy: "当前未启用在线支付。订单已安全提交，客服将通过你选择的渠道确认付款与交付。",
    orderNo: "订单号",
    reservedUntil: "库存保留至",
    backHome: "返回首页",
    openSupport: "联系商家",
    lookupTitle: "查询你的订单",
    lookupCopy: "输入订单号和下单时的联系方式，安全查看处理进度。",
    query: "查询订单",
    querying: "正在安全查询",
    lookupMissing: "请填写订单号和原始联系方式",
    lookupInvalid: "订单号格式不正确",
    lookupNotFound: "没有找到匹配订单，请检查订单号和联系方式",
    productIntro: "商品介绍",
    processingTime: "人工处理 · 预计 10–30 分钟响应",
    humanConnection: "人工服务",
    serviceNotes: "服务说明",
    currencyTokens: "云桥币种标识",
    supportBridge: "客服连接",
    checkoutBridge: "单一联系方式下单",
    connectionEstablished: "连接已建立",
    secureOrderLookup: "安全订单查询",
    policyEyebrow: "云桥 / 政策",
    notFoundEyebrow: "未找到此连接",
    footerLegal: "© 2026 CloudBridge. 仅用于设计预览。",
    capability: ["全球币种", "双价格桥接", "单联系方式下单", "人工服务接力"],
    capabilityCopy: ["识别地区，也可手动切换", "当地货币与 USDT 同时呈现", "无需商城注册与复杂资料", "订单进入后台后由客服跟进"],
  },
  en: {
    brandName: "CloudBridge",
    homeLabel: "CloudBridge home",
    previousStory: "Previous",
    nextStory: "Next",
    capabilitiesLabel: "CloudBridge capabilities",
    languageChinese: "Chinese",
    languageEnglish: "English",
    brandLine: "Connecting global AI services",
    orderLookup: "Find order",
    contactSupport: "Support",
    productsTitle: "AI service gallery",
    productsCopy: "Leading AI tools presented with clear pricing and live inventory states.",
    discoverTitle: "Which AI service would you like to connect?",
    searchProducts: "Search by product name",
    categoryAll: "All",
    noResultsTitle: "No matching services found",
    noResultsCopy: "Try a shorter keyword or choose another category.",
    clearSearch: "Clear search",
    serviceCapabilities: "Service capabilities",
    currentCurrency: "Currency",
    allServices: "All services",
    localPrice: "Local price",
    usdtReference: "USDT reference",
    stock: "Inventory",
    inStock: "Available",
    lowStock: "Only {count} left",
    soldOut: "Sold out",
    buyNow: "Place order",
    viewDetail: "View details",
    contactTitle: "Need clarity first? Connect with support",
    contactCopy: "Choose your preferred channel for product, payment and delivery questions.",
    footerLine: "Connecting tools, pricing and trusted service.",
    privacy: "Privacy",
    terms: "Terms",
    refund: "Refund policy",
    delivery: "Digital delivery",
    cookies: "Cookies & tracking",
    language: "Language",
    currency: "Currency",
    autoRecommend: "Suggested for your region",
    buyTitle: "Submit order",
    contactType: "Contact channel",
    contactValue: "Contact details",
    submitOrder: "Confirm order",
    submitting: "Connecting order",
    consent: "By submitting, you allow the merchant to use this contact to process the order.",
    requiredError: "Enter your contact details",
    formatError: "The contact format looks incorrect",
    successTitle: "Order awaiting manual review",
    successCopy: "Online payment is currently disabled. Your order is saved and support will confirm payment and delivery through your chosen channel.",
    orderNo: "Order number",
    reservedUntil: "Reserved until",
    backHome: "Back home",
    openSupport: "Contact merchant",
    lookupTitle: "Find your order",
    lookupCopy: "Enter the order number and original contact details to view progress securely.",
    query: "Find order",
    querying: "Checking securely",
    lookupMissing: "Enter the order number and original contact details",
    lookupInvalid: "The order number format is incorrect",
    lookupNotFound: "No matching order was found. Check the order number and contact details.",
    productIntro: "Product introduction",
    processingTime: "Human-assisted · Typical response in 10–30 min",
    humanConnection: "HUMAN CONNECTION",
    serviceNotes: "SERVICE NOTES",
    currencyTokens: "CLOUDBRIDGE TOKENS",
    supportBridge: "SUPPORT BRIDGE",
    checkoutBridge: "ONE-CONTACT CHECKOUT",
    connectionEstablished: "CONNECTION ESTABLISHED",
    secureOrderLookup: "SECURE ORDER LOOKUP",
    policyEyebrow: "CLOUDBRIDGE / POLICY",
    notFoundEyebrow: "BRIDGE NOT FOUND",
    footerLegal: "© 2026 CloudBridge. Preview design only.",
    capability: ["Global currencies", "Dual-price bridge", "One-contact checkout", "Human service relay"],
    capabilityCopy: ["Region-aware with manual switching", "Local currency and USDT together", "No store account or long form", "Support follows up from the console"],
  },
};
